version: '3'

networks:
  holago-production-network:
    driver: bridge

services:
  holago_production_backend:
    container_name: holago_production_backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile # Path to your Dockerfile for Holago backend
    networks:
      - holago-production-network
    env_file:
      - .env # Environment variables for Holago backend
    volumes:
      - .:/app
    ports:
      - '103.191.51.223:5000:8080' # Port mapping for Holago backend
    depends_on:
      - holago_production_mongo

  holago_production_mongo:
    container_name: holago_production_mongo
    restart: always
    image: mongo
    ports:
      - '103.191.51.223:9090:27017' # Port mapping for MongoDB
    networks:
      - holago-production-network
    volumes:
      - /home/holago_persistent/mongodb:/data/db
    env_file:
      - .env

  holago_production_mongo_express:
    container_name: holago_production_mongo_express
    image: mongo-express
    restart: always
    ports:
      - '103.191.51.223:8081:8081' # Port mapping for Mongo Express
    networks:
      - holago-production-network
    env_file:
      - .env
    depends_on:
      - holago_production_mongo

volumes:
  cache:
